server:
  port: 8080
datasource:
  username: root
  password: 123456
  url: tcp(localhost:3306)/tiktok?charset=utf8mb4&parseTime=True&loc=Local
redis:
  host: localhost
  port: 6379
  password: 123456