server:
  port: 8000
datasource:
  username: root
  password: 12345678
  url: tcp(localhost:3306)/tiktok?charset=utf8mb4&parseTime=True&loc=Local
oss:
  endPoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tEpSNFxcFEjyCSm3a7b
  accessKeySecret: CI7WsknlLCfm1pKaKcJDve99LmXh9G
  bucketName: java2go
  domain: https://java2go.oss-cn-hangzhou.aliyuncs.com/