server:
  port: 8080
datasource:
  username: root
  password: 123456
  url: tcp(localhost:3306)/douyin?charset=utf8mb4&parseTime=True&loc=Local
redis:
  host: localhost
  port: 6379
  password: 123456
oss:
  endPoint : oss-cn-hangzhou.aliyuncs.com
  accessKeyId : LTAI5tEpSNFxcFEjyCSm3a7b
  accessKeySecret : CI7WsknlLCfm1pKaKcJDve99LmXh9G
  bucketName : java2go
  domain : https://java2go.oss-cn-hangzhou.aliyuncs.com/